import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * 사이드바는 docs/ 폴더 구조에서 자동 생성한다.
 * 순서·이름은 각 폴더의 `_category_.json`과 문서 프런트매터(`sidebar_position`)로 정한다.
 * MkDocs의 `.pages`(awesome-pages 플러그인)가 하던 일을 대신한다.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
